
version: '3.8'

services:
  mongo:
    image: leogloriainfnet/aurora-mongo
    container_name: aurora-mongo2
    ports:
       - "27017:27017"
    networks: 
      - sb_net
  postgres:
    image: leogloriainfnet/aurora-postgres
    container_name: pg-aurora2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aurora
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - sb_net

  pyspark:
    build: .
    container_name: pyspark2
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - '9999:8888'
      - '4040:4040'
    volumes:
      - ./data:/work
    networks:
      - sb_net

  spark:
    image: docker.io/bitnami/spark:3.5
    container_name: spark2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./data:/work
    networks:
      - sb_net
  
  spark-worker-1:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-work-1_2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./data:/work
    networks:
      - sb_net
    depends_on:
      - spark
  
  spark-worker-2:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-work-2_2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./data:/work
    networks:
      - sb_net
    depends_on:
      - spark

networks:
  sb_net:
    driver: bridge

name: projeto-pyspark-mongo-postgres